### PR TITLE
add xsl extension

### LINKED ISSUE #62: xsl extension
Symfony 4.4 has a new mailer component with a default template https://symfony.com/blog/new-in-symfony-4-4-notification-emails
This default template uses a few components, one of which is [pinky]https://packagist.org/packages/lorenzo/pinky) which requires the xsl php extension.

Basically I want to suggest adding the xsl extension.

### PR DESCRIPTION
**Pull request by Nemo64**
This resolves #62 although i probably should wait for #61.

### CODE REVIEW

**Comment by Nemo64** [comment]
The failure seems to be related to xdebug.

**Comment by le0m** [comment]
Thanks for the PR! I'll look into It in the next days.

About the failure, PECL xdebug recently dropped PHP 7.0 support with version 2.9.1. I'll fix it in another PR.

**Comment by le0m** [comment]
Hello again, I've merged #61. If you update this to use the new script I'll merge this too :)

**Comment by Nemo64** [comment]
I updated the commit.

**Pull request merged**
