### PR TITLE
✨ Add PHP 5.4-dev (with Xdebug)

### PR DESCRIPTION
**Pull request by nstCactus**

### CODE REVIEW

**Comment by fquffio** [comment]
Hi @nstCactus! Thanks a lot for your contribution, I appreciate that a lot! I’ll be reviewing your PR tomorrow early in the morning, to get it merged as soon as possible.

Could you please update `.travis.yml` and `dev/README.md` as well? In case you can’t, no problem — I can do that tomorrow as I run a couple of tests.

**Comment by nstCactus** [comment]
Hi @fquffio!
I made the changes and amended my commit.
Thank you for dealing with this so quickly!

**Comment by fquffio** [comment]
Ok, I've set up the automatic build on Docker Cloud. `chialab/php-dev:5.4` images should become available shortly after merging this PR.

Travis build is still failing, but that's due to PHP 5.5 and PHP 5.6 not being able to install latest version of XDebug, thus it's unrelated to this PR, and I'll be fixing that in the morning.

Thanks a lot, @nstCactus, for your interest in this project and your contribution!

**Comment by nstCactus** [comment]
About the Xdebug error for PHP 5.6 and PHP 5.5 I was about to create an issue for this. You just need to specify the Xdebug version number.
I think the latest compatible Xdebug version is 2.5.5 for both.

**Comment by fquffio** [comment]
Yes, I think you're right. I opened PR #29. It's quite trivial, however if you had some time to make a review of it, it would be appreciated!

**Pull request merged**
